####single variable logistic Regression
- 가설함수 : $ h(x) = wx + b $
- sigmoid == logistic 함수 : $ sigmoid(x) = \frac{1}{1+exp^{-x}} $
- binary cross entropy :
    - 1) 확률함수변형 : $ P(C=1 | x) = y, P(C=0 | x) = 1-y, P(C=t | x) = y^t(1-y)^{1-t} $
    - 2) likelyhood : $ L(w,b) = Π_{i=0}^{n}P(C=t_i | x_i)=y^t(1-y)^{1-t}$
    - 3) negative log-likely hood : $ Σ_{i=0}^n -tlog(y_i)log(1-y_i) $
- gradient update : $w = w - α * {\frac{\partial{Cost(w,b)}}{\partial{w}}} $

#1. 데이터 준비

In [24]:
import numpy as np
x_data = np.array([2,4,6,8,10,12,14,16,18,20]).reshape(10,1)
t_data = np.array([0,0,0,0,0,0,1,1,1,1]).reshape(10,1)

print("x_data.shape = ", x_data.shape, ", y_data.shape = ", y_data.shape)

x_data.shape =  (10, 1) , y_data.shape =  (10, 1)


In [25]:
x_data

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20]])

In [26]:
t_data

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])

# 2. 데이터 전처리, Scale, 표준화, train/test split

#3. 모델 : 가설함수 구현(hypo, sigmoid, lf ...)

- 가설함수 : $ h(x) = wx + b $

In [27]:
W = np.random.rand(1,1)
b = np.random.rand(1)

def hypoF(X):
    return np.dot(X, W) + b

In [28]:
hypoF(np.array([[3]]))

array([[2.30286613]])

In [29]:
W

array([[0.57408164]])

In [30]:
b

array([0.58062121])

- sigmoid == logistic 함수 : $ sigmoid(z) = \frac{1}{1+exp^{-z}} $

In [31]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [32]:
z = hypoF(np.array([[150]]))

In [33]:
sigmoid(z)

array([[1.]])

# 4. Loss function : binary cross entropy
 - $ P(C = 1 | x) = y, P(C = 0 | x) = 1-y, P(C = t | x ) = y^{t} * (1 - y)^{1-t}$
 - likelyhood : $ L(W, b) = \Pi_{i = 0}^{n}P(C = t_i | x_i) = \Pi_{i = 0}^{n}y^{t} * (1 - y)^{1-t} $ t=sigmoid output, y=target
 - negative log likely hood : $ \sum_{i = 0}^{n} - t * log(y) - (1-t) log(1-y) $

In [34]:
def bce(X, target):

    z = np.dot(X, W) + b
    y_hat = sigmoid(z)

    return np.sum(-target * np.log(y_hat) - (1-target) * np.log(1-y_hat))

In [35]:
bce(x_data, t_data)

27.839309729297515

# 5. Gradient

In [50]:
# loss대비, parameter (W,b)값의 기울기가 어떤가
def gradient(bceF, param):
    h = 1e-5
    grads = np.zeros_like(param)

    for idx in range(param.size):
        tmp = param[idx]
        param[idx] = tmp + h
        l_f = bceF(param)

        param[idx] = tmp - h
        l_b = bceF(param)

        grads[idx] = ( l_f - l_b ) / (2 * h)
        param[idx] = tmp
    
    return grads

In [51]:
bcef = lambda x : bce(x_data, t_data)

In [52]:
bcef

<function __main__.<lambda>(x)>

# 6. gradient update
- $ w = w - \alpha \frac{\partial{Cost(W, b)}}{\partial{W}} $,  $ \alpha $ = learning rate

In [57]:
learning_rate = 0.01

for idx in range(10000):
    grad_w = gradient(bcef, W)
    grad_b = gradient(bcef, b)
    W = W - learning_rate * grad_w
    b = b - learning_rate * grad_b
    loss = bce(x_data, t_data)

    print("epoch : ", idx, "Loss 값 : ", loss, "W값 : ", W, "b값 : ", b)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
epoch :  5000 Loss 값 :  0.659498770694082 W값 :  [[1.10058952]] b값 :  [-14.17952304]
epoch :  5001 Loss 값 :  0.6594647188991043 W값 :  [[1.10063383]] b값 :  [-14.18010307]
epoch :  5002 Loss 값 :  0.659430672059228 W값 :  [[1.10067814]] b값 :  [-14.18068305]
epoch :  5003 Loss 값 :  0.6593966301731595 W값 :  [[1.10072245]] b값 :  [-14.181263]
epoch :  5004 Loss 값 :  0.6593625932395859 W값 :  [[1.10076676]] b값 :  [-14.1818429]
epoch :  5005 Loss 값 :  0.6593285612572253 W값 :  [[1.10081106]] b값 :  [-14.18242276]
epoch :  5006 Loss 값 :  0.6592945342247797 W값 :  [[1.10085536]] b값 :  [-14.18300258]
epoch :  5007 Loss 값 :  0.6592605121409669 W값 :  [[1.10089965]] b값 :  [-14.18358236]
epoch :  5008 Loss 값 :  0.6592264950044562 W값 :  [[1.10094394]] b값 :  [-14.18416209]
epoch :  5009 Loss 값 :  0.6591924828139688 W값 :  [[1.10098823]] b값 :  [-14.18474178]
epoch :  5010 Loss 값 :  0.6591584755682021 W값 :  [[1.10103252]] b값 :  [-14.18532143]
epoch :  5011 Loss 값 :  0.65912447

In [69]:
new_input = np.array([13])
z = hypoF(new_input)
z

array([0.11405854])

In [70]:
y_hat = sigmoid(z)
y_hat

array([0.52848376])

# Lambda Function

In [72]:
exam1 = lambda x : x * x
exam1(3)

9

In [75]:
exam2 = lambda y : (x_data, t_data)

In [77]:
exam2(100)

(array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12],
        [14],
        [16],
        [18],
        [20]]), array([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1]]))

In [84]:
C = 15
def plus(a, b) :
    return a + b + C

In [85]:
plus(1, 2)

18

In [86]:
exam3 = lambda y : plus(3,5)

In [89]:
C = 50
exam3(1)

58